apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: santi-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: santi-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/santiagovm/tap-03-hackathon
      ref:
        branch: main
